### PR TITLE
180-fix-doubled-logs

### LINKED ISSUE #180: Bug: After restart filed pod logs are duplicated
**Describe the bug**
After recreating pod with filed it's duplicate big amount of logs.

**To Reproduce**
1. Run config with file input plugin
2. Put message from different streams - 'a', 'b', 'c' for example
3. Delete pod or process
4. Filed reads all logs from oldest offset.

**Expected behavior**
Read files from newest offset.
**Additional context**
Version: v0.6.0
Platform: linux, mac

### PR DESCRIPTION
**Pull request by ansakharov**
No more double logs after restart file / k8s input plugin

Fixes #180

### CODE REVIEW

File: plugin/input/file/worker.go [hunk 1]
```diff
@@ -109,7 +110,15 @@ func (w *worker) work(controller inputer, jobProvider *jobProvider, readBufferSi
 						accumBuf = append(accumBuf, line...)
 						inBuf = accumBuf
 					}
-					job.lastEventSeq = controller.In(sourceID, sourceName, lastOffset+scanned, inBuf, isVirgin)
+
+					currOffset := lastOffset + scanned
```
Comment (vano144) [inline plugin/input/file/worker.go:114]: need more comments here)

Comment (ansakharov) [reply plugin/input/file/worker.go:114]: After discuss we chose different apporach.

File: pipeline/pipeline.go [hunk 2]
```diff
@@ -450,6 +450,12 @@ func (p *Pipeline) streamEvent(event *Event) uint64 {
 		if node != nil {
 			event.streamName = StreamName(node.AsString())
 		}
+
```
Comment (vano144) [inline pipeline/pipeline.go:453]: https://github.com/ozontech/file.d/pull/182/files#diff-78caab79060ca671036a14efcebed6637079dfd826728fcbdfd856540c3d04f4R433 Now it should be in streamEvent after check. Since now we will output all events

File: plugin/input/dmesg/dmesg.go [hunk 3]
```diff
@@ -136,3 +136,8 @@ func (p *Plugin) Commit(event *pipeline.Event) {
 		p.logger.Error("can't save offset file: %s", err.Error())
 	}
 }
+
+// PassEvent decides pass or discard event.
+func (p *Plugin) IsPassedEvent(event *pipeline.Event) bool {
```
Comment (vano144) [inline plugin/input/dmesg/dmesg.go:141]: PassEvent or IsPassedEvent ?

Comment (ansakharov) [reply plugin/input/dmesg/dmesg.go:141]: Fixed that naming: linux based file leak on Mac

File: pipeline/pipeline.go (hunk 2 above)
Comment (ansakharov) [reply pipeline/pipeline.go:453]: well this it is in streamEvent.

**Review by vadimalekseev — APPROVED** [review]
LGTM!

**Review by vano144 — APPROVED** [review]
