### PR TITLE
Fix modify plugin

### LINKED ISSUE #561: Bug: Incorrect modify plugin
**Describe the bug**
The modify plugin doesn't work as described in the documentation.

**To Reproduce**
1. Get config from [doc](https://github.com/ozontech/file.d/blob/master/plugin/action/modify/README.md)
2. Run file.d with this config
3. Instead of replacing the value of the nested field `my_object.field.subfield` - the plugin adds a new field to the root with a name containing "."

**Expected behavior**
The plugin must correctly replace the values of fields whose depth level is greater than 1.

### PR DESCRIPTION
**Pull request by kirillov6**
Fixes #561

### CODE REVIEW

File: plugin/action/modify/modify.go [hunk 1]
```diff
@@ -92,7 +100,12 @@ func (p *Plugin) Do(event *pipeline.Event) pipeline.ActionResult {
 			}
 		}
 
-		event.Root.AddFieldNoAlloc(event.Root, field).MutateToBytesCopy(event.Root, p.buf)
+		node := event.Root.Dig(fo.field...)
+		if node == nil {
+			node = event.Root.AddFieldNoAlloc(event.Root, field)
```
Comment (HeadHunter483) [inline plugin/action/modify/modify.go:105]: Seems like it will add single field `field.subfield` but we want to add nested field `field`->`subfield`. And it would be great to have a test for that case.

Comment (kirillov6) [reply plugin/action/modify/modify.go]: done

**Review by HeadHunter483 — APPROVED** [review]
LGTM!

**Review by vadimalekseev — APPROVED** [review]

**Review by vano144 — APPROVED** [review]
