### PR TITLE
Reset busy action after Hold

### LINKED ISSUE #278: Bug: We must reset previous action after Propagate
**Describe the bug**
Now we are not reset action busy status after ActionHold.

**To Reproduce**

```yaml
pipelines:
  ingresslogs:
    actions:
      - continue: /(^\w+)/
        field: message
        start: /^\d{1,10}#\d{1,10}\:.*/
        type: join
      - type: discard
    input:
      dir_pattern: '*'
      filename_pattern: error.log
      offsets_file: configs/ingresslog-offsets.yaml
      type: file
      watching_dir: configs/logs
    output:
      type: devnull
    settings:
      capacity: 30
      decoder: nginx_error
```

```sh
$ while true; do echo "2023/01/25 08:27:27 [error] request: \"$(date +%s) POST /\", upstream: \"g\", host: \"ams\"" >> configs/logs/error.log; sleep 0.0001; done
```

It will panic after 30 seconds.

**Additional context**
Version: all
Platform: all

### PR DESCRIPTION
**Pull request by vadimalekseev**
Fixes #278

### CODE REVIEW

File: pipeline/processor.go [hunk 1]
```diff
@@ -351,8 +351,10 @@ func (p *processor) Commit(event *Event) {
 	p.finalize(event, false, true)
 }
 
+// Propagate flushes an event after ActionHold.
 func (p *processor) Propagate(event *Event) {
```
Comment (vadimalekseev) [inline pipeline/processor.go:355]: Let's rename `Propagate` -> `PropagateHolded`/`ReleaseEvent`/something else

**Review by vitkovskii — APPROVED** [review]

File: pipeline/processor.go (hunk 1 above)
Comment (vadimalekseev) [reply pipeline/processor.go:351]: @vitkovskii, hey! What do you think about this?)

**Review by HeadHunter483 — APPROVED** [review]
LGTM!
