### PR TITLE
Superfluous call fix

### LINKED ISSUE #276: Bug: superfluous response.WriteHeader call
```
http: superfluous response.WriteHeader call from github.com/ozontech/file.d/pipeline.(*Pipeline).serveActionSample.func1 (pipeline.go:799)
```

### PR DESCRIPTION
**Pull request by vadimalekseev**
Fixes #276

### CODE REVIEW

File: pipeline/action_watcher.go [hunk 1]
```diff
@@ -110,7 +110,11 @@ func (aw *actionWatcher) setEventBefore(index int, event *Event) {
 		if s == nil || len(s.eventBefore) > 0 {
 			continue
 		}
-		s.eventBefore = event.Root.EncodeToByte()
+
+		s.eventBefore = []byte("<timeout event>")
```
Comment (vano144) [inline pipeline/action_watcher.go:114]: What do you think about creation this slice only once? For example, we can create global var here

**Review by vano144 — APPROVED** [review]

**Review by HeadHunter483 — APPROVED** [review]
LGTM!

**Review by vano144 — APPROVED** [review]
