### PR TITLE
Fix panic /pipelines/<name>

### LINKED ISSUE #96: Bug: eventPool.dump panics
**Describe the bug**
eventPool.dump panics when`/pipelines/<name>` is called.

**To Reproduce**
1. eventPoll must be busy;
2. call `/pipelines/<name>` to trigger `.dump()`;

**Expected behavior**
It shouldn't panic.

**Additional context**
Version: v0.5.2
Stack trace:
```
2022/05/26 08:15:03 http: panic serving 10.37.201.234:51522: runtime error: invalid memory address or nil pointer dereference
goroutine 1328031 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:1802 +0xb9
--
goroutine 1328031 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:1802 +0xb9
panic({0x144d100, 0x22cf530})
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1047 +0x266
github.com/ozontech/file.d/pipeline.(*Event).String(0x15fb4a7)
	/Users/skiritsa/go/src/file.d/pipeline/event.go:189 +0x27
github.com/ozontech/file.d/pipeline.(*eventPool).dump.func1()
	/Users/skiritsa/go/src/file.d/pipeline/event.go:300 +0x53
github.com/ozontech/file.d/logger.Cond(...)
	/Users/skiritsa/go/src/file.d/logger/util.go:25
github.com/ozontech/file.d/pipeline.(*eventPool).dump(0xc000314200)
	/Users/skiritsa/go/src/file.d/pipeline/event.go:296 +0x65
github.com/ozontech/file.d/pipeline.(*Pipeline).servePipeline(0xc000134580, {0x18186d8, 0xc0057542a0}, 0x0)
	/Users/skiritsa/go/src/file.d/pipeline/pipeline.go:627 +0x106
net/http.HandlerFunc.ServeHTTP(0x0, {0x18186d8, 0xc0057542a0}, 0x0)
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x18186d8, 0xc0057542a0}, 0xc00ab80e00)
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc0079ab1d0}, {0x18186d8, 0xc0057542a0}, 0xc00ab80e00)
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc007fca780, {0x1823eb8, 0xc000551a40})
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:3034 +0x4e8
```

### PR DESCRIPTION
**Pull request by vadimalekseev**
# Description

This fixes the eventPool.dump panic.

Fixes #96

### CODE REVIEW

File: pipeline/event.go [hunk 1]
```diff
@@ -297,6 +298,9 @@ func (p *eventPool) dump() string {
 		o := logger.Header("events")
 		for i := 0; i < p.freeEventsCount; i++ {
 			event := p.events[i]
+			if event == nil {
+				continue
```
Comment (ansakharov) [inline pipeline/event.go]: Let's print `nil` event. 
Otherwise eventPool [m, m1, m2] will be dumped as string: `m.String()\nm2.String()\n` while expecting `m.String()\nnil\nm2.String()\n`

Comment (ssnd) [reply pipeline/event.go]: we could also log an error in case this happens

Comment (aleksvdim) [reply pipeline/event.go]: > we could also log an error in case this happens

Is not an error, event may nil if pool is busy. Should we log this?

Comment (ssnd) [reply pipeline/event.go]: okay I agree, it's not necessary here

File: pipeline/event.go [hunk 2]
```diff
@@ -186,6 +187,9 @@ func (e *Event) kindStr() string {
 }
 
 func (e *Event) String() string {
+	if e == nil {
+		return "nil"
```
[the remark this answers is not in the document]
Comment (aleksvdim) [reply pipeline/event.go:191]: @ansakharov and I [decided](https://github.com/ozontech/file.d/pull/97#discussion_r882522165) that we wanted to write "nil". Maybe we should move "nil" higher?

File: longpanic/longpanic.go [hunk 3]
```diff
@@ -46,6 +53,13 @@ type LongPanic struct {
 
 // NewLongPanic creates LongPanic.
 func NewLongPanic(timeout time.Duration) *LongPanic {
+	// Because NewLongPanic is called at the package level, there will be a panic if stats is not initialized
+	stats.InitStats()
```
Comment (aleksvdim) [inline longpanic/longpanic.go:57]: Any ideas to make it better? :)

**Comment by aleksvdim** [comment]
> Is it really necessary to have more than one panic handler function?
